import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast"; // Allow for toast notifications in the app

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
	return (
		<html lang="en">
			<head>
			</head>
				<body className={inter.className}>
					<Toaster/>
					{children}
				</body>
		</html>
	);
}
